services:
  york_sensor_app:
    container_name: york_sensor_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@york_sensor_db:5432/postgres
      - APP_CONFIG=production
      - FLASK_APP=app
    command: >
       bash -c "sleep 5 &&
              if [ ! -d 'migrations' ]; then 
                flask db init; 
              fi &&
              flask db migrate -m 'Auto migration' || true &&
              flask db upgrade || true &&
              flask run --host=0.0.0.0 --port=4000"

              

              
    depends_on:
      - york_sensor_db
  york_sensor_db:
    container_name: york_sensor_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}